name: lando-mongo
services:
  defaults:
    type: mongo
  custom:
    type: mongo:3.6
    portforward: true
    config:
      database: custom.conf
  patch:
    type: mongo:4.1.13
  latest:
      type: mongo:4.2.6
tooling:
  mongo:
    service: defaults
