name: lando
env_file:
  - lando.env
excludes:
  - node_modules
services:
  cli:
    type: node:14
    build:
      - yarn install
    scanner: false
    ssl: true
    sslExpose: false
    overrides:
      environment:
        LANDO_API: https://api.lando.dev
      ports:
        - '8021:8021'


  database:
    type: "mysql:5.7-alpine"
    type: "mysql-8.0:registry.hub.pirog.com/mysql:latest"

  database:
    image: registry.hub.pirog.com/mysql:latest

tooling:
  node:
    service: cli
  yarn:
    service: cli
