[build]
  base = "./"
  publish = "_docs"
  command = "yarn build"
  # This sort of lets us build only on tagged commits to prod
  # [context.production]
  #   ignore = "if git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep - | grep version && git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep + | grep version; then exit 1; else exit 0; fi"

# Domain redirects
[[redirects]]
  from = "https://docs.lndo.io/*"
  to = "https://docs.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://docs.devwithlando.io/*"
  to = "https://docs.lando.dev/:splat"
  status = 301

# Legacy redirects from cloudflare
[[redirects]]
  from = "https://docs.lando.dev/contrib/how.html"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/issues/*"
  to = "https://docs.lando.dev/help/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/tutorials/*"
  to = "https://docs.lando.dev/config/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/dev/*"
  to = "https://docs.lando.dev/contrib/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/started.html"
  to = "https://docs.lando.dev/basics/"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/installation/*"
  to = "https://docs.lando.dev/basics/installation.html"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/cli/*"
  to = "https://docs.lando.dev/basics/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/troubleshooting/*"
  to = "https://docs.devwithlando.io/help/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/config/config.html"
  to = "https://docs.lando.dev/config/global.html"
  status = 301
