name: lando-pma
services:
  pma:
    type: phpmyadmin:5.0
    hosts:
      - database
      - database2
  pma_legacy:
    type: phpmyadmin:4.7
    hosts:
      - database
      - database2
  database:
    type: mariadb
  database2:
    type: mariadb
