name: Ship macOS Installer

on:
  push:
    branches:
      - main
      - 'preview/**'
    tags:
      - test*
      - v*

jobs:
  build-macos-test:
    runs-on: ${{ matrix.os }}
    env:
      APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_TEAM_ID: FY8GAUX282
      TERM: xterm
    strategy:
      matrix:
        os:
          - macos-10.15
        node-version:
          - '14'
    steps:
      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Import ENVVARS from build.env
      # @NOTE: We do this so there is a single place to update versions
      - name: Import build version envvars
        id: import-env
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < BUILD.env

      # Build and prep the release
      - name: Rewrite the version based on the tag
        run: |
          node scripts/dev-version.js
          node ./bin/lando.js version
      - name: Import and verify certs
        run: scripts/import-macos-certs.sh
      - name: Assemble pieces
        run: scripts/assemble-macos.sh
      - name: Sign package
        run: |
          # Rename some things
          mv build/installer/dmg/LandoInstaller.pkg build/installer/dmg/UnsignedLandoInstaller.pkg
          # Sign
          productsign --sign "$APPLE_TEAM_ID" build/installer/dmg/UnsignedLandoInstaller.pkg build/installer/dmg/LandoInstaller.pkg
          # Verify
          pkgutil --check-signature build/installer/dmg/LandoInstaller.pkg
          # Remove unsigned
          rm -f build/installer/dmg/UnsignedLandoInstaller.pkg
      - name: Create DMG
        run: |
          mkdir -p dist
          scripts/create-dmg.sh build/installer/dmg
      - name: Sign DMG
        run: |
          # Sign
          codesign -s "$APPLE_TEAM_ID" -v dist/lando.dmg
          # Verify
          codesign -v dist/lando.dmg
      - name: Notarize DMG
        env:
          APPLE_NOTARY_USER: ${{ secrets.APPLE_NOTARY_USER }}
          APPLE_NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}
        run: scripts/notarize.sh dist/lando.dmg

      # Create and upload releases
      - name: Create releases
        env:
          SOURCE_BRANCH: "${GITHUB_REF#refs/heads/}"
          SOURCE_TAG: "$(git describe --tags --abbrev=0)"
        shell: bash
        run: |
          # Create release directories
          mkdir -p ./releases ./dev-builds

          # Snapshot release
          cp -f "./dist/lando.dmg" "./dev-builds/lando-build-${{ github.sha }}.dmg"

          # Branch releases
          if [ -z "$SOURCE_TAG" ]; then cp -f "./dist/lando.dmg" "./releases/lando-$SOURCE_BRANCH-latest.dmg"; fi
          # Latest dev release
          if [[ "$SOURCE_BRANCH" == "main" ]]; then cp -f "./dist/lando.dmg" "./releases/lando-latest.dmg"; fi
          # Tag releases
          if [ ! -z "$SOURCE_TAG" ]; then cp -f "./dist/lando.dmg" "./releases/lando-$SOURCE_TAG.dmg"; fi
          # Latest stable release
          if [ ! -z "$SOURCE_TAG" ]; then cp -f "./dist/lando.dmg" "./releases/lando-stable.dmg"; fi

          # Print what we end up with
          ls -lsa ./releases
          ls -lsa ./dev-builds
